apiVersion: v1
kind: Service
metadata:
  name: learn-kubernetes-app
  labels:
    app.kubernetes.io/component: web
spec:
  selector:
    app: learn-kubernetes-app
    app.kubernetes.io/name: learn-kubernetes-app
    app.kubernetes.io/component: web

  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: web

  clusterIP: 10.43.197.165
